<a href="https://colab.research.google.com/github/Nehadasmk/NaturalLanguageProcessing/blob/main/Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 paragraph = """ Natural Language Processing (NLP) is a fascinating field of study! It's a branch of artificial intelligence (AI) that focuses on the interaction between computers and humans through natural language. NLP involves several tasks such as text analysis, sentiment analysis, machine translation, and much more. In recent years, the advancements in NLP have been remarkable, with technologies like GPT-3 making headlines. Email: example@example.com. Visit us at http://www.example.com for more information. """

In [ ]:
paragraph

" Natural Language Processing (NLP) is a fascinating field of study! It's a branch of artificial intelligence (AI) that focuses on the interaction between computers and humans through natural language. NLP involves several tasks such as text analysis, sentiment analysis, machine translation, and much more. In recent years, the advancements in NLP have been remarkable, with technologies like GPT-3 making headlines. Email: example@example.com. Visit us at http://www.example.com for more information. "

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
##tokenization -- convrts paragraphs - sentences -words
nltk.download('punkt')
sentences = nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
print(sentences)

[' Natural Language Processing (NLP) is a fascinating field of study!', "It's a branch of artificial intelligence (AI) that focuses on the interaction between computers and humans through natural language.", 'NLP involves several tasks such as text analysis, sentiment analysis, machine translation, and much more.', 'In recent years, the advancements in NLP have been remarkable, with technologies like GPT-3 making headlines.', 'Email: example@example.com.', 'Visit us at http://www.example.com for more information.']


In [ ]:
stemmer = PorterStemmer()

In [ ]:
stemmer.stem('history')

'histori'

In [ ]:
stemmer.stem('goes')

'goe'

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
lemmatizer.lemmatize('goes')

'go'

In [ ]:
lemmatizer.lemmatize('history')

'history'

In [ ]:
##Removing stop words from sentences
len(sentences)


6

In [ ]:
import re

In [ ]:
corpus=[]
for sent in sentences:
  print(sent)

 Natural Language Processing (NLP) is a fascinating field of study!
It's a branch of artificial intelligence (AI) that focuses on the interaction between computers and humans through natural language.
NLP involves several tasks such as text analysis, sentiment analysis, machine translation, and much more.
In recent years, the advancements in NLP have been remarkable, with technologies like GPT-3 making headlines.
Email: example@example.com.
Visit us at http://www.example.com for more information.


In [ ]:
for sent in sentences:
  review = re.sub('[^a-zA-Z]',' ',sent) # removing evry special charcter other than [^a-zA-Z@.] and replacing thwm with space " "
  review = review.lower()
  corpus.append(review)


In [ ]:
corpus

[' natural language processing  nlp  is a fascinating field of study ',
 'it s a branch of artificial intelligence  ai  that focuses on the interaction between computers and humans through natural language ',
 'nlp involves several tasks such as text analysis  sentiment analysis  machine translation  and much more ',
 'in recent years  the advancements in nlp have been remarkable  with technologies like gpt   making headlines ',
 'email  example example com ',
 'visit us at http   www example com for more information ']

In [ ]:
nltk.download('stopwords')
stopwords = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#stemming
for doc in corpus:
  words = nltk.word_tokenize(doc)
  for word in words:
    if word not in stopwords:
      print(stemmer.stem(word))

natur
languag
process
nlp
fascin
field
studi
branch
artifici
intellig
ai
focus
interact
comput
human
natur
languag
nlp
involv
sever
task
text
analysi
sentiment
analysi
machin
translat
much
recent
year
advanc
nlp
remark
technolog
like
gpt
make
headlin
email
exampl
exampl
com
visit
us
http
www
exampl
com
inform


In [ ]:
##lemmatization
for doc in corpus:
  words = nltk.word_tokenize(doc)
  for word in words:
    if word not in stopwords:
      print(lemmatizer.lemmatize(word))

natural
language
processing
nlp
fascinating
field
study
branch
artificial
intelligence
ai
focus
interaction
computer
human
natural
language
nlp
involves
several
task
text
analysis
sentiment
analysis
machine
translation
much
recent
year
advancement
nlp
remarkable
technology
like
gpt
making
headline
email
example
example
com
visit
u
http
www
example
com
information


In [ ]:
##Doing the above steps step - wise

import re
corpus=[]

for i in range (len(sentences)):
  review = re.sub('[^a-zA-Z]',' ',sentences[i])
  review = review.lower()
  review = review.split() # gets each sentences
  review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['natural language processing nlp fascinating field study',
 'branch artificial intelligence ai focus interaction computer human natural language',
 'nlp involves several task text analysis sentiment analysis machine translation much',
 'recent year advancement nlp remarkable technology like gpt making headline',
 'email example example com',
 'visit u http www example com information']

In [ ]:
#Bag Of Words
from sklearn.feature_extraction.text import CountVectorizer # to extract features from text
cv = CountVectorizer(binary =True,ngram_range=(2,3)) #includes both bigram and trigram


In [ ]:
x = cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_

{'natural language': 45,
 'language processing': 38,
 'processing nlp': 53,
 'nlp fascinating': 47,
 'fascinating field': 21,
 'field study': 23,
 'natural language processing': 46,
 'language processing nlp': 39,
 'processing nlp fascinating': 54,
 'nlp fascinating field': 48,
 'fascinating field study': 22,
 'branch artificial': 10,
 'artificial intelligence': 8,
 'intelligence ai': 32,
 'ai focus': 2,
 'focus interaction': 24,
 'interaction computer': 34,
 'computer human': 13,
 'human natural': 30,
 'branch artificial intelligence': 11,
 'artificial intelligence ai': 9,
 'intelligence ai focus': 33,
 'ai focus interaction': 3,
 'focus interaction computer': 25,
 'interaction computer human': 35,
 'computer human natural': 14,
 'human natural language': 31,
 'nlp involves': 49,
 'involves several': 36,
 'several task': 61,
 'task text': 63,
 'text analysis': 67,
 'analysis sentiment': 6,
 'sentiment analysis': 59,
 'analysis machine': 4,
 'machine translation': 42,
 'translation muc

In [ ]:
corpus[0]

'natural language processing nlp fascinating field study'

In [ ]:
len(x[0].toarray())

1

In [ ]:
ar = x[0].toarray()

In [ ]:
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
len(ar[0]) # size of the vocabullary in teh alpbabetic order were ever we found the match to vocabulary we gave 1 at that index

76

In [ ]:
x.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0

In [ ]:
## an example for the above



from sklearn.feature_extraction.text import CountVectorizer

# Sample text
text = ["Natural language processing is fascinating."]

# Create the CountVectorizer with ngram_range (2, 3)
vectorizer = CountVectorizer(ngram_range=(2, 3))

# Fit and transform the text
X = vectorizer.fit_transform(text)

# Get the feature names (the n-grams)
features = vectorizer.get_feature_names_out()

# Convert the result to an array
X_array = X.toarray()

# Display the results
print("N-grams:", features)
print("BoW Representation:\n", X_array)





N-grams: ['is fascinating' 'language processing' 'language processing is'
 'natural language' 'natural language processing' 'processing is'
 'processing is fascinating']
BoW Representation:
 [[1 1 1 1 1 1 1]]


In [ ]:
vectorizer.vocabulary_ # vocabulary length == BOW length


{'natural language': 3,
 'language processing': 1,
 'processing is': 5,
 'is fascinating': 0,
 'natural language processing': 4,
 'language processing is': 2,
 'processing is fascinating': 6}

The unique 2-grams and 3-grams found in the text are:
These aere based on the alphabetic order

"is fascinating"
"language processing"
"language processing is"
"natural language"
"natural language processing"
"processing is"
"processing is fascinating"
BoW Representation
The BoW vector representing the frequency of each n-gram is:
[1,1,1,1,1,1,1]

This means that each of the listed n-grams appears exactly once in the sample text. Here’s the breakdown:

"is fascinating": 1 occurrence
"language processing": 1 occurrence
"language processing is": 1 occurrence
"natural language": 1 occurrence
"natural language processing": 1 occurrence
"processing is": 1 occurrence
"processing is fascinating": 1 occurrence
This vector representation can be used in various natural language processing tasks such as text classification, clustering, and more. ​

In [ ]:
##TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(ngram_range=(2,3)) #max_feature can be used to get the features that are presented many tumes like if 3 or 5 or 10
X = cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_

{'natural language': 45,
 'language processing': 38,
 'processing nlp': 53,
 'nlp fascinating': 47,
 'fascinating field': 21,
 'field study': 23,
 'natural language processing': 46,
 'language processing nlp': 39,
 'processing nlp fascinating': 54,
 'nlp fascinating field': 48,
 'fascinating field study': 22,
 'branch artificial': 10,
 'artificial intelligence': 8,
 'intelligence ai': 32,
 'ai focus': 2,
 'focus interaction': 24,
 'interaction computer': 34,
 'computer human': 13,
 'human natural': 30,
 'branch artificial intelligence': 11,
 'artificial intelligence ai': 9,
 'intelligence ai focus': 33,
 'ai focus interaction': 3,
 'focus interaction computer': 25,
 'interaction computer human': 35,
 'computer human natural': 14,
 'human natural language': 31,
 'nlp involves': 49,
 'involves several': 36,
 'several task': 61,
 'task text': 63,
 'text analysis': 67,
 'analysis sentiment': 6,
 'sentiment analysis': 59,
 'analysis machine': 4,
 'machine translation': 42,
 'translation muc

In [ ]:
corpus[0]

'natural language processing nlp fascinating field study'

In [ ]:
X[0]

<1x76 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [ ]:
ar = X[0].toarray()

In [ ]:
ar

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30610363, 0.30610363, 0.30610363, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.30610363, 0.30610363,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.25100935, 0.30610363, 0.30610363, 0.30610363, 0.        ,
        0.        , 0.        , 0.        , 0.30610363, 0.30610363,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [ ]:
len(ar[0
       ])

76